<?php
/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function open_saou_ting_client_webservice() {
  $ret = array();
  $ret['saou']['class'] = 'open_saou';
  $ret['saou']['url'] = 'open_saou_url';
  $ret['soau']['xsd_url'] = 'open_saou_xsd';
  $ret['saou']['xsdNamespace'] = array(0=>'http://ws.saouservice.dbc.dk');
  return $ret;
}

/** Implements hook_formID_alter
 *
 * Adds settings for adhl service client
 *
 * @see ting_client_admin_webservices_settings
 * in ting_client.admin.inc
 *
 * @param $form
 * @param $form_state
 */
function open_saou_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['saou'] = array(
    '#type' => 'fieldset',
    '#title' => 'saou settings',
    '#description' => t('The saou service is used to get atuhentication for restricted ressources'),
    '#collapsible' => TRUE,
    '#tree' => FALSE,
  );
  $form['saou']['open_saou_url'] = array(
    '#type' => 'textfield',
    '#title' => t('saou service URL'),
    '#description' => t('URL to Open saou webservice , e.g. http://saou.addi.dk/saouWebService/SaouWebService?wsdl'),
    '#required' => TRUE,
    '#default_value' => variable_get('open_saou_url', ''),
  );
  $form['saou']['open_saou_xsd'] = array(
    '#type' => 'textfield',
    '#title' => t('saou service XSD URL'),
    '#description' => t('URL to XSD to Open saou webservice , e.g. http://saou.addi.dk/saouWebService/SaouWebService?xsd=1'),
    '#required' => TRUE,
    '#default_value' => variable_get('open_saou_xsd', ''),
  );
}