<?php
/**
 * Developer notes:
 * best documentation found: http://wiki.dbc.dk/bin/view/Net/SaouProjektWiki
 * Example client: http://saou.addi.dk/saouservice-web/index.jsp
 * Flow diagram : http://wiki.dbc.dk/pub/Net/SaouProjektWiki/SAOU.pdf
 *
 * soqpUI is also en excellent example client
 */

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function open_saou_ting_client_webservice() {
  $ret = array();
  $ret['saou']['class'] = 'open_saou';
  $ret['saou']['url'] = 'open_saou_url';
  return $ret;
}

/** Implements hook_formID_alter
 *
 * Adds settings for adhl service client
 *
 * @see ting_client_admin_webservices_settings
 * in ting_client.admin.inc
 *
 * @param $form
 * @param $form_state
 */
function open_saou_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['saou'] = array(
    '#type' => 'fieldset',
    '#title' => 'saou settings',
    '#description' => t('The saou service is used to get atuhentication for restricted ressources'),
    '#collapsible' => TRUE,
    '#tree' => FALSE,
  );
  $form['saou']['open_saou_url'] = array(
    '#type' => 'textfield',
    '#title' => t('saou service wsdl URL'),
    '#description' => t('URL to Open saou webservice wsdl , e.g. http://saou.addi.dk:80/saouWebService/SaouWebService?wsdl'),
    '#required' => TRUE,
    '#default_value' => variable_get('open_saou_url', ''),
  );
  $form['saou']['open_saou_xsd'] = array(
    '#type' => 'textfield',
    '#title' => t('saou service XSD URL'),
    '#description' => t('URL to XSD to Open saou webservice , e.g. http://saou.addi.dk/saouWebService/SaouWebService?xsd=1'),
    '#required' => TRUE,
    '#default_value' => variable_get('open_saou_xsd', ''),
  );
}

/** execute FetchLicenseByPidRequest.Fetch all allowed ressource by given pid
 *
 * @param $pid
 * @param array $agencyAndUserIds; MUST be of the form: array('agencyUserId'=>array($agencyId, $userId))
 * @param $municipalityNr
 *
 * @return string(xml) whatever response service delivers
 */
/*
 developer note. Can not make this one work -- where to get municipalityNr
 */
function open_saou_FetchLicenseByPid($pid, array $agencyAndUserIds, $municipalityNr){
  $fetchLicensesByPidRequest = array(
    'pid' => $pid,
    'agencyAndUserIds' => $agencyAndUserIds,
    'municipalityNr' => $municipalityNr,
  );
  $params['action'] = 'FetchLicenseByPid';
  $params['fetchLicensesByPidRequest'] = $fetchLicensesByPidRequest;
  return open_saou_do_request($params);
}

/** Do FetchLicensesByAgencyId request. Fetch all allowed ressource by given agencyID
 * @param $agencyId
 * @return string(xml)
 */
function open_saou_FetchLicensesByAgencyId($agencyId){
  $params['FetchLicensesByAgencyId'] = array(
    'AgencyId' => $agencyId,
  );

  return open_saou_do_request($params);
}

/** Do FetchAgencyIdsByBaseIdent. Get all agencies with access to given identifier
 * @param $baseIdent (string)
 * @return string(xml)
 */
function open_saou_FetchAgencyIdsByBaseIdent($baseIdent){
  $params['FetchAgencyIdsByBaseIdent'] = array(
    'BaseId' => $baseIdent,
  );

  return open_saou_do_request($params);
}

/** Execute saou request from given parameters
 *
 * @param $params
 * @return string(xml)
 */
function open_saou_do_request($params){
  $client = new ting_client_class();
  $response = $client->do_request('saou', $params);

  return $response;
}





